name: ci
on:
    push:
        branches: [develop]

jobs:
    lint:
        runs-on: [self-hosted, linux, x64]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: lint
              run: php -l *.php

